//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace pointSalesv1.Models.puntoVenta
{

    public partial class entrada : XPLiteObject
    {
        long fidEntrada;
        [Key(true)]
        public long idEntrada
        {
            get { return fidEntrada; }
            set { SetPropertyValue<long>(nameof(idEntrada), ref fidEntrada, value); }
        }
        DateTime ffecha;
        public DateTime fecha
        {
            get { return ffecha; }
            set { SetPropertyValue<DateTime>(nameof(fecha), ref ffecha, value); }
        }
        double ftotal;
        public double total
        {
            get { return ftotal; }
            set { SetPropertyValue<double>(nameof(total), ref ftotal, value); }
        }
        proveedores fid_proveedor;
        [Association(@"entradaReferencesproveedores")]
        public proveedores id_proveedor
        {
            get { return fid_proveedor; }
            set { SetPropertyValue<proveedores>(nameof(id_proveedor), ref fid_proveedor, value); }
        }
        [Association(@"detalle_entradaReferencesentrada")]
        public XPCollection<detalle_entrada> detalle_entradas { get { return GetCollection<detalle_entrada>(nameof(detalle_entradas)); } }

       
    }

}
