//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace pointSalesv1.Models.puntoVenta
{

    public partial class estado : XPLiteObject
    {
        int fidstado;
        [Key(true)]
        public int idstado
        {
            get { return fidstado; }
            set { SetPropertyValue<int>(nameof(idstado), ref fidstado, value); }
        }
        string festado1;
        [Size(45)]
        [Persistent(@"estado")]
        public string estado1
        {
            get { return festado1; }
            set { SetPropertyValue<string>(nameof(estado1), ref festado1, value); }
        }
        [Association(@"perdidaReferencesestado")]
        public XPCollection<perdida> perdidas { get { return GetCollection<perdida>(nameof(perdidas)); } }
        [Association(@"productosReferencesestado")]
        public XPCollection<productos> productosCollection { get { return GetCollection<productos>(nameof(productosCollection)); } }
        [Association(@"ventaReferencesestado")]
        public XPCollection<venta> ventas { get { return GetCollection<venta>(nameof(ventas)); } }
    }

}
