//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace pointSalesv1.Models.puntoVenta
{

    public partial class perdida : XPLiteObject
    {
        int fidPerdida;
        [Key(true)]
        public int idPerdida
        {
            get { return fidPerdida; }
            set { SetPropertyValue<int>(nameof(idPerdida), ref fidPerdida, value); }
        }
        estado fid_estado;
        [Association(@"perdidaReferencesestado")]
        public estado id_estado
        {
            get { return fid_estado; }
            set { SetPropertyValue<estado>(nameof(id_estado), ref fid_estado, value); }
        }
        DateTime ffecha;
        public DateTime fecha
        {
            get { return ffecha; }
            set { SetPropertyValue<DateTime>(nameof(fecha), ref ffecha, value); }
        }
        double ftotalPerdida;
        public double totalPerdida
        {
            get { return ftotalPerdida; }
            set { SetPropertyValue<double>(nameof(totalPerdida), ref ftotalPerdida, value); }
        }
        [Association(@"detalle_perdidaReferencesperdida")]
        public XPCollection<detalle_perdida> detalle_perdidas { get { return GetCollection<detalle_perdida>(nameof(detalle_perdidas)); } }
    }

}
