//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace pointSalesv1.Models.puntoVenta
{
    [Serializable]
    public partial class productos : XPLiteObject
    {
        int fidProductos;
        [Key(true)]
        public int idProductos
        {
            get { return fidProductos; }
            set { SetPropertyValue<int>(nameof(idProductos), ref fidProductos, value); }
        }
        string fcodigo;
        [Indexed(Name = @"codigo")]
        [Size(45)]
        public string codigo
        {
            get { return fcodigo; }
            set { SetPropertyValue<string>(nameof(codigo), ref fcodigo, value); }
        }
        string fnombre;
        public string nombre
        {
            get { return fnombre; }
            set { SetPropertyValue<string>(nameof(nombre), ref fnombre, value); }
        }
        estado fid_estado;
        [Association(@"productosReferencesestado")]
        public estado id_estado
        {
            get { return fid_estado; }
            set { SetPropertyValue<estado>(nameof(id_estado), ref fid_estado, value); }
        }
        categoria fid_categoria;
        [Association(@"productosReferencescategoria")]
        public categoria id_categoria
        {
            get { return fid_categoria; }
            set { SetPropertyValue<categoria>(nameof(id_categoria), ref fid_categoria, value); }
        }
        marcas fid_marcas;
        [Association(@"productosReferencesmarcas")]
        public marcas id_marcas
        {
            get { return fid_marcas; }
            set { SetPropertyValue<marcas>(nameof(id_marcas), ref fid_marcas, value); }
        }
        double fcosto;
        public double costo
        {
            get { return fcosto; }
            set { SetPropertyValue<double>(nameof(costo), ref fcosto, value); }
        }
        int fstock;
        public int stock
        {
            get { return fstock; }
            set { SetPropertyValue<int>(nameof(stock), ref fstock, value); }
        }
        double fprecio;
        public double precio
        {
            get { return fprecio; }
            set { SetPropertyValue<double>(nameof(precio), ref fprecio, value); }
        }
        tipounidad ftipoUnidad;
        [Association(@"productosReferencestipounidad")]
        public tipounidad tipoUnidad
        {
            get { return ftipoUnidad; }
            set { SetPropertyValue<tipounidad>(nameof(tipoUnidad), ref ftipoUnidad, value); }
        }
        [Association(@"detalle_entradaReferencesproductos")]
        public XPCollection<detalle_entrada> detalle_entradas { get { return GetCollection<detalle_entrada>(nameof(detalle_entradas)); } }
        [Association(@"detalle_ventaReferencesproductos")]
        public XPCollection<detalle_venta> detalle_ventas { get { return GetCollection<detalle_venta>(nameof(detalle_ventas)); } }
    }

}
