//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace pointSalesv1.Models.puntoVenta
{

    public partial class proveedores : XPLiteObject
    {
        int fidProveedores;
        [Key(true)]
        public int idProveedores
        {
            get { return fidProveedores; }
            set { SetPropertyValue<int>(nameof(idProveedores), ref fidProveedores, value); }
        }
        string fcodigo;
        [Size(6)]
        public string codigo
        {
            get { return fcodigo; }
            set { SetPropertyValue<string>(nameof(codigo), ref fcodigo, value); }
        }
        string fempresa;
        [Size(70)]
        public string empresa
        {
            get { return fempresa; }
            set { SetPropertyValue<string>(nameof(empresa), ref fempresa, value); }
        }
        string frazon;
        [Size(80)]
        public string razon
        {
            get { return frazon; }
            set { SetPropertyValue<string>(nameof(razon), ref frazon, value); }
        }
        string fdireccion;
        public string direccion
        {
            get { return fdireccion; }
            set { SetPropertyValue<string>(nameof(direccion), ref fdireccion, value); }
        }
        string ftelefono;
        [Size(12)]
        public string telefono
        {
            get { return ftelefono; }
            set { SetPropertyValue<string>(nameof(telefono), ref ftelefono, value); }
        }
        [Association(@"entradaReferencesproveedores")]
        public XPCollection<entrada> entradas { get { return GetCollection<entrada>(nameof(entradas)); } }
    }

}
